### ISSUE TITLE
Connections not being closed in latest version

### ISSUE THREAD

**Issue by ilushka85** [fluentcassandra/fluentcassandra#82] opened 2012-10-22 23:59 UTC
The latest version with connection pooling set to false causes connections to remain open.

This is verified by viewing netstat on client and server.

**Comment by nberardi** [comment] 2012-10-23 00:12
Please show your code. Connections will stay open if you are using a session.

**Comment by ilushka85** [comment] 2012-10-23 00:14
Even when the session is disposed of?

What is the purpose of the session?

**Comment by nberardi** [comment] 2012-10-23 00:16
I didn't say that. Show your code to verify this. Because I don't see this problem.

**Comment by ilushka85** [comment] 2012-10-23 00:20
public class DataStorageMapperBase : FluentCommonBase, IDisposable
    {

  public DataStorageMapperBase()
        {
            var builder = new ConnectionBuilder(ConfigurationManager.AppSettings["DataConnectionString"]);

```
       // cs = new CassandraSession(builder);
        db = new CassandraContext(builder);
    }


    public void Dispose()
    {

        if (db != null)
        {
            db.Dispose();
            db = null;
        }
    }
```

}

  public abstract class FluentCommonBase
    {
        protected CassandraContext db = null;

}

When we use it all together:

 public class UserStorageMapper : DataStorageMapperBase //: StorageMapper
    {

```
    public UserStorageMapper() : base() { }

    public void Dispose()
    {
        base.Dispose();
    }
```

 public User GetUserByUserID(Guid userID)
        {
            try
            {

```
            var userIDResult = usernameByIDColumnFamily.Get(userID).FirstOrDefault();
            if (userIDResult.IsNullOrEmptyFluent()) return null;

            var userResult = usersColumnFamily.Get((string)userIDResult.Columns[0].ColumnName).FirstOrDefault();
            if (userResult.IsNullOrEmptyFluent()) return null;

            return ColumnReflector.CreateObjectFromColumns(userResult.Columns, typeof(User)) as User;
        }
        catch (Exception ex)
        {
            SiAuto.Main.LogException(thisStorageMapper + "GetUserByUserID()", ex);
            return null;
        }
    }
```

}

We call the function getuserbyuserid inside a using statement of userstoragemapper

**Comment by ilushka85** [comment] 2012-10-23 00:24
Looks like fluentcassandraconnections.connection dispose method is never being called by cassandracontext

**Comment by ilushka85** [comment] 2012-10-23 00:26
Also appears that despite my config saying pooling=false  its actually set to true... checking why as that would make sense for connections staying open.

**Comment by ilushka85** [comment] 2012-10-23 00:32
So appears that the connections do close properly with pooling off but problem is they sit in time_Wait state so that wont work if a lot are openned frequently.

**Comment by ilushka85** [comment] 2012-10-23 00:59
So heres what i have found.... when calls get executed on the server pooledconnection provider does not release them until the context is closed...

so it means the following....

   rows = usersColumnFamily.Get().TakeKeys(pageSize);

lastKey = (string)rows.Last().Key;

 foreach (var row in rows)
                {

}

The above code requires opening 2 connections..... in the case of the pooled provider 2 connections must be available or openned in the pool....

so the above code would not work if maxpoolsize is set to 1.  Although there is nothing stopping it from working if the connection in the pool is released after the first execute function(lastKey = (string)rows.Last().Key;)  is ran on the server.

**Comment by ilushka85** [comment] 2012-10-23 01:06
Any thoughts on why its this way?  Examining the code leads to nothing removing connections from being in use in pool until a session or context is closed / disposed

**Comment by nberardi** [comment] 2012-10-23 01:45
None of that is right. The point of a connection pool is to keep
connections open and ready to the server so you don't have to wait for a
connection. So you don't close the connection you just return it to the
pool.

First the session is responsible for closing connections or returning them
back to the pool.

https://github.com/managedfusion/fluentcassandra/blob/master/src/CassandraSession.cs#L225

Secondly the session is open and disposed on the execution of a command.
Unless you provide your own session. For the context.

https://github.com/managedfusion/fluentcassandra/blob/master/src/CassandraContext.cs#L369

Lastly. The pooling doesn't default to on. It defaults to off.

https://github.com/managedfusion/fluentcassandra/blob/master/src/Connections/ConnectionBuilder.cs#L108

I am not quite sure what the issue is you are experiencing. But you should
probably review issue #29 because much of how this works has been discussed
there.

## 

Nick Berardi
(484) 302-0125
Sent from my tablet.

On Oct 22, 2012, at 8:59 PM, ilushka85 notifications@github.com wrote:

So heres what i have found.... when calls get executed on the server
pooledconnection provider does not release them until the context is
closed...

so it means the following....

rows = usersColumnFamily.Get().TakeKeys(pageSize);

lastKey = (string)rows.Last().Key;

foreach (var row in rows)
{

}

The above code requires opening 2 connections..... in the case of the
pooled provider 2 connections must be available or openned in the pool....

so the above code would not work if maxpoolsize is set to 1. Although there
is nothing stopping it from working if the connection in the pool is
released after the first execute function(lastKey =
(string)rows.Last().Key;) is ran on the server.

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/82#issuecomment-9686505.

**Comment by ilushka85** [comment] 2012-10-23 02:33
By closing i meant releasing(the function is just called close)

What i notice:

https://github.com/managedfusion/fluentcassandra/blob/master/src/CassandraContext.cs#L369 

This line for disposal when called has _connection as null so therefore its never released.  checking why its null now.

**Comment by nberardi** [comment] 2012-10-23 02:56
Do you mean _session or did you reference the wrong class?

## 

Nick Berardi
(484) 302-0125
Sent from my tablet.

On Oct 22, 2012, at 10:33 PM, ilushka85 notifications@github.com wrote:

By closing i meant releasing(the function is just called close)

What i notice:

https://github.com/managedfusion/fluentcassandra/blob/master/src/CassandraContext.cs#L369

This line for disposal when called has _connection as null so therefore its
never released. checking why its null now.

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/82#issuecomment-9687923.

**Comment by ilushka85** [comment] 2012-10-23 02:57
Well _session is not null and _Connection is.  It appears same issue described in #29 ... still figure out how to solve it its pretty big because of the lazy loading aspect.

**Comment by ilushka85** [comment] 2012-10-23 03:10
Its what: edweip3  mentioned in #29.  Was there ever a fix for this?

**Comment by ilushka85** [comment] 2012-10-23 03:24
The problem is that the session is disposed before its connection is set.

This can be tested by debuging the code and when it hits the following line in getcolumnfamilyrangeslices

var output = Session.GetClient().get_range_slices(
                parent,
                SlicePredicate,
                KeyRange,
                Session.ReadConsistency
            );

looking at Session has the property wasdisposed=true

and in this case .getclient() is what will create the connection and since its already disposed it wont get disposed again.

**Comment by nberardi** [comment] 2012-10-23 11:55
I would have to see the code you are running.

## 

Nick Berardi
(484) 302-0125
Sent from my tablet.

On Oct 22, 2012, at 11:24 PM, ilushka85 notifications@github.com wrote:

The problem is that the session is disposed before its connection is set.

This can be tested by debuging the code and when it hits the following line
in getcolumnfamilyrangeslices

var output = Session.GetClient().get_range_slices(
parent,
SlicePredicate,
KeyRange,
Session.ReadConsistency
);

looking at Session has the property wasdisposed=true

and in this case .getclient() is what will create the connection and since
its already disposed it wont get disposed again.

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/82#issuecomment-9689631.

**Comment by ilushka85** [comment] 2012-10-23 12:23
Heres a simple test that demonstrates this:

  var builder = new ConnectionBuilder(ConfigurationManager.AppSettings["ResultlyDataConnectionString"]);

```
        var db = new CassandraContext(builder);



        CassandraColumnFamily usersColumnFamily = new CassandraColumnFamily<UTF8Type>(db, "Users");


        for (int x = 0; x < 100; x++)
        {
            var rows = usersColumnFamily.Get().TakeKeys(25);
            string lastKey = rows.Last().Key;


            Console.WriteLine(lastKey);
        }
```

**Comment by ilushka85** [comment] 2012-10-23 13:04
Just like posted in issue #29 

If you put Session.GetClient(); inside of the execute function like in GetColumnFamilyRangeSlices.cs

Then it gets properly disposed / released etc...

**Comment by ilushka85** [comment] 2012-10-23 13:09
This still doesnt seem to entirely solve the issue however.

**Comment by ilushka85** [comment] 2012-10-23 13:18
Willing to pay a bounty if someone can fix this issue today.

**Comment by ilushka85** [comment] 2012-10-23 15:37
My crude attempt at fixing this was inserting the following snippets in each of the operation function classes

  var temp = output.GetEnumerator();
            if (Session.WasDisposed)
            {
                Session.WasDisposed = false;
                Session.Dispose();
            }

example - getsupercolumnfamilyrangeslices.cs

```
public override IEnumerable<FluentSuperColumnFamily> Execute()
    {
        var schema = ColumnFamily.GetSchema();

        var parent = new CassandraColumnParent {
            ColumnFamily = ColumnFamily.FamilyName
        };

        SlicePredicate = Helper.SetSchemaForSlicePredicate(SlicePredicate, schema, SuperColumnName == null);

        var output = Session.GetClient().get_range_slices(
            parent,
            SlicePredicate,
            KeyRange,
            Session.ReadConsistency
        );
        var temp = output.GetEnumerator();
        if (Session.WasDisposed)
        {
            Session.WasDisposed = false;
            Session.Dispose();
        }
        foreach (var result in output)
        {
            var key = CassandraObject.GetCassandraObjectFromDatabaseByteArray(result.Key, schema.KeyValueType);

            var r = new FluentSuperColumnFamily(key, ColumnFamily.FamilyName, schema, result.Columns.Select(col => {
                var superCol = Helper.ConvertSuperColumnToFluentSuperColumn(col.Super_column, schema);
                ColumnFamily.Context.Attach(superCol);
                superCol.MutationTracker.Clear();

                return superCol;
            }));
            ColumnFamily.Context.Attach(r);
            r.MutationTracker.Clear();

            yield return r;
        }
    }
```

**Comment by ilushka85** [comment] 2012-10-23 15:37
In some of the functions the getenumerator can be skipped.  by doing this in all the operation methods like above it ensures that connections are properly released.... its not the most elegant method but it works for time being.

additional needed to change WasDisposed of session to not make the set private.

**Comment by ilushka85** [comment] 2012-10-25 22:27
Any luck at looking at this?

**Comment by nberardi** [comment] 2012-10-25 22:32
Haven't had time to look at it

**Comment by ilushka85** [comment] 2012-10-26 17:54
Also it appears if an exception occurs on a connection like a timeout then it does not get returned to the pool either.

**Comment by nberardi** [comment] 2012-11-13 20:29
Merging into issue #29

**Closed as completed by nberardi** 2012-11-13 20:29 UTC
